// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServicoFaturamento.Infrastructure;

#nullable disable

namespace ServicoFaturamento.Migrations
{
    [DbContext(typeof(FaturamentoDbContext))]
    [Migration("20260831171637_InitialCreate_Faturamento")]
    partial class InitialCreate_Faturamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServicoFaturamento.Domain.ItemNotaFiscal", b =>
                {
                    b.Property<long>("NotaFiscalNumero")
                        .HasColumnType("bigint");

                    b.Property<string>("CodigoProduto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("NotaFiscalNumero", "CodigoProduto");

                    b.ToTable("ItensNotaFiscal", "faturamento");
                });

            modelBuilder.Entity("ServicoFaturamento.Domain.NotaFiscal", b =>
                {
                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Numero"));

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Numero");

                    b.ToTable("NotasFiscais", "faturamento");
                });

            modelBuilder.Entity("ServicoFaturamento.Domain.ItemNotaFiscal", b =>
                {
                    b.HasOne("ServicoFaturamento.Domain.NotaFiscal", null)
                        .WithMany("Itens")
                        .HasForeignKey("NotaFiscalNumero")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServicoFaturamento.Domain.NotaFiscal", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
